/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author keert
 */
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
public class Patientdetailsinfo extends javax.swing.JFrame {

    /**
     */
    String userid;
    public Patientdetailsinfo() {
        initComponents();
    }
    public Patientdetailsinfo(String name) 
{
        userid=name;
        initComponents();
        
        
    
//    
//        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
//        String b[]={"gayu","22i218","12345678","160","50","9876543210"};
//        model.addRow(b);
    
        try {
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/hospital" ,"root","root");
            Statement stmt=con.createStatement();
            String x="Select * from patientdetails;";
            ResultSet rs=stmt.executeQuery(x);
            while(rs.next())
            {
                if(userid.equals(rs.getString(2)))
                {
                    System.out.println("Hello"+rs.getString(1));
                    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                    String a[]={"Name",rs.getString(1)};
                    model.addRow(a);
                    String b[]={"User Name ",rs.getString(2)};
                    model.addRow(b);
//                    String c[]={"Name",rs.getString(3)};
//                    model.addRow(c);
                    String d[]={"Height",rs.getString(4)};
                    model.addRow(d);
                    String e[]={"Weight",rs.getString(5)};
                    model.addRow(e);
                   String f[]={"Blood Group",rs.getString(6)};
                    model.addRow(f);
                    String g[]={"Phone Number ",rs.getString(7)};
                    model.addRow(g);
                    String h[]={"Remarks",rs.getString(8)};
                    model.addRow(h);
                    
                    
//                    String a[]={"Name",rs.getString(1)};
//                    model.addRow(a);
                }
            }
            
            
//            ArrayList<String> name=new ArrayList<>();
//            ArrayList<String> username=new ArrayList<>();
//            ArrayList<String> password=new ArrayList<>();
//            ArrayList<String> height=new ArrayList<>();
//            ArrayList<String> weight=new ArrayList<>();
//            ArrayList<String> phoneno=new ArrayList<>();
//            ArrayList<String> remarks=new ArrayList<>();
            
          //  String x="select * from patientdetails where name ='"+name+"';";
         // ResultSet rs=stmt.executeQuery("Select * from patientdetails");
         
//          String quer1 = "select *from patientdetails where username ?";
//          PreparedStatement ps = con.prepareStatement(quer1);
//          ps.setString(1,username);
//          
//          ResultSet rs = ps.executeQuery();
//          
//          while(rs.next())
//          {
//              
//              
//              //System.out.println(rs.getString("name"));
//          }
          
          
            
//            ResultSet rs=stmt.executeQuery(x);
//            while(rs.next())
//            {
//                password.add(rs.getString(3));
//                username.add(rs.getString(2));
//                name.add(rs.getString(1));
//                height.add(rs.getString(4));
//                weight.add(rs.getString(5));
//                phoneno.add(rs.getString(6));
//                remarks.add(rs.getString(7));
//            }
//            int n=name.size();
//            for(int i=0;i<n;i++)
//                
//            {
//                String a[]={name.get(i),username.get(i),password.get(i)+height.get(i)+weight.get(i)+phoneno.get(i)+remarks.get(i)};
//                model.addRow(a);
//            }
        } catch (Exception e) {
            Logger.getLogger(Appview.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FieldName", "Entries"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patientdetailsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patientdetailsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patientdetailsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patientdetailsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patientdetailsinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
   //  String username;
}
